const dialogues=[
 {scene:'Você encontrou uma amiga.',zh:'你好',pinyin:'Nǐ hǎo',tones:['nǐ · 3º ∨','hǎo · 3º ∨'],tip:'Duas curvas: a voz desce e volta a subir.',hint:'Cumprimento usado quando encontramos alguém.'},
 {scene:'Ela pergunta como você está.',zh:'你好吗',pinyin:'Nǐ hǎo ma?',tones:['nǐ · 3º ∨','hǎo · 3º ∨','ma · neutro'],tip:'O “ma” final é curto, leve e sem força.',hint:'Pergunta curta sobre como a pessoa está.'},
 {scene:'Você responde que está muito bem.',zh:'我很好',pinyin:'Wǒ hěn hǎo',tones:['wǒ · 3º ∨','hěn · 3º ∨','hǎo · 3º ∨'],tip:'Imite a frase inteira; tons seguidos se ajustam na fala natural.',hint:'Resposta positiva para a pergunta anterior.'},
 {scene:'Agora você pergunta “e você?”.',zh:'你呢',pinyin:'Nǐ ne?',tones:['nǐ · 3º ∨','ne · neutro'],tip:'Faça “ne” curto e leve.',hint:'Serve para devolver a pergunta.'},
 {scene:'Você diz seu nome.',zh:'我叫 Eva',pinyin:'Wǒ jiào Eva',tones:['wǒ · 3º ∨','jiào · 4º ↘'],tip:'“Jiào” começa alto e cai com firmeza.',hint:'Use esta fala para se apresentar.'},
 {scene:'Você se despede.',zh:'再见',pinyin:'Zàijiàn',tones:['zài · 4º ↘','jiàn · 4º ↘'],tip:'As duas sílabas caem com energia.',hint:'Use quando a conversa terminar.'}
];
const vocab={'Animais':[['狗','gǒu','cachorro','3º ∨'],['猫','māo','gato','1º —'],['熊猫','xióngmāo','panda','2º ↗ · 1º —'],['鸟','niǎo','pássaro','3º ∨'],['鱼','yú','peixe','2º ↗'],['马','mǎ','cavalo','3º ∨']],'Cores':[['红色','hóngsè','vermelho','2º ↗ · 4º ↘'],['蓝色','lánsè','azul','2º ↗ · 4º ↘'],['绿色','lǜsè','verde','4º ↘ · 4º ↘'],['黄色','huángsè','amarelo','2º ↗ · 4º ↘'],['白色','báisè','branco','2º ↗ · 4º ↘'],['黑色','hēisè','preto','1º — · 4º ↘']],'Verbos':[['吃','chī','comer','1º —'],['喝','hē','beber','1º —'],['去','qù','ir','4º ↘'],['来','lái','vir','2º ↗'],['看','kàn','ver','4º ↘'],['说','shuō','falar','1º —']],'Essenciais':[['水','shuǐ','água','3º ∨'],['厕所','cèsuǒ','banheiro','4º ↘ · 3º ∨'],['帮助','bāngzhù','ajuda','1º — · 4º ↘'],['谢谢','xièxie','obrigada','4º ↘ · neutro'],['对不起','duìbuqǐ','desculpe','4º ↘ · neutro · 3º ∨']]};
const state={index:0,stars:0,attempts:0,correct:0,minutes:0,classTime:'17:00',offDays:[],...JSON.parse(localStorage.getItem('forevar')||'{}')};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let timerId,seconds=1800;
function save(){localStorage.setItem('forevar',JSON.stringify(state));renderStats()}function speak(text,rate=.68){if(!('speechSynthesis'in window)){alert('Use Chrome ou Edge para ouvir.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';u.rate=rate;speechSynthesis.speak(u)}
function renderDialogue(){const d=dialogues[state.index];$('#dialogueStep').textContent=`FALA ${state.index+1} DE ${dialogues.length}`;$('#scene').textContent=d.scene;$('#tonePath').innerHTML=d.tones.map(x=>`<span class="tone">${x}</span>`).join('');$('#toneTip').textContent=d.tip;$('#helpBox').innerHTML=`<b>${d.pinyin}</b><br>${d.hint}`;$('#helpBox').classList.add('hidden');$('#speechResult').className='speech-result';$('#speechResult').textContent='Ouça quantas vezes precisar e depois responda.';$('#prevDialogue').disabled=state.index===0}
function recognize(target,out){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){out.textContent='O microfone com avaliação exige Chrome ou Edge.';out.className='speech-result retry';return}const r=new SR();r.lang='zh-CN';r.maxAlternatives=3;r.onstart=()=>{out.textContent='Estou ouvindo… fale agora.'};r.onresult=e=>{state.attempts++;const heard=[...e.results[0]].map(x=>x.transcript.replace(/[。！？\s]/g,''));const goal=target.replace(/[。！？\s]/g,'');const ok=heard.some(x=>x.includes(goal)||goal.includes(x));if(ok){state.correct++;state.stars+=3;out.textContent='Ótimo! O app reconheceu sua fala. Ouça outra vez e compare os tons. +3 ⭐';out.className='speech-result good'}else{out.textContent=`Tente novamente. O aparelho entendeu “${heard[0]}”. Ouça e imite o ritmo completo.`;out.className='speech-result retry'}save()};r.onerror=()=>{out.textContent='Não consegui ouvir. Confira a permissão do microfone.';out.className='speech-result retry'};r.start()}
function renderWords(){const cat=$('#category').value||Object.keys(vocab)[0];$('#wordGrid').innerHTML=vocab[cat].map((w,i)=>`<article class="word-card"><h3>${w[2]}</h3><p>Movimento: ${w[3]}</p><div class="word-actions"><button data-speak="${w[0]}">🔊 Ouvir</button><button class="mic" data-word="${w[0]}" data-id="${i}">🎙️ Repetir</button></div><p class="word-feedback" id="wf${i}"></p></article>`).join('');$$('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak,.64));$$('[data-word]').forEach(b=>b.onclick=()=>recognize(b.dataset.word,$('#wf'+b.dataset.id)))}
function renderRoutine(){const message='Oi, Eva! 🐼 Que horas você fará seus 30 minutos de mandarim hoje? O horário combinado é 17h. Se hoje não puder, marque no app. Sua mãe poderá pausar o uso do celular se a lição não for feita. Não é para deixar você triste: é só uma ajuda para cumprir primeiro o combinado e depois usar o celular tranquila. Você consegue! 💜';$('#dailyMessage').textContent=message;$('#offList').innerHTML=state.offDays.length?state.offDays.map(d=>`<span class="off-chip">📅 ${new Date(d+'T12:00').toLocaleDateString('pt-BR')}</span>`).join(''):'<span class="small">Nenhuma indisponibilidade marcada.</span>';$('#classTime').value=state.classTime}
function renderStats(){$('#stars').textContent=state.stars;$('#minutes').textContent=state.minutes;$('#attempts').textContent=state.attempts;$('#correct').textContent=state.correct}
function startTimer(){if(timerId)return;$('#timer').classList.remove('hidden');$('#startClass').textContent='Aula em andamento';timerId=setInterval(()=>{seconds--;$('#clock').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;if(seconds%60===0){state.minutes++;save()}if(seconds<=0){clearInterval(timerId);state.stars+=10;save();alert('Aula concluída! 30 minutos de mandarim falado. 太棒了!')}},1000)}
function todayOff(){const d=new Date().toISOString().slice(0,10);return state.offDays.includes(d)}function scheduleCheck(){const now=new Date(),h=now.getHours(),m=now.getMinutes();if(todayOff())return;const key=now.toISOString().slice(0,10);if(h===13&&m===0&&localStorage.getItem('ask-'+key)!=='1'){notify('forEVAr — aula de hoje',$('#dailyMessage').textContent);localStorage.setItem('ask-'+key,'1')}const [ch,cm]=state.classTime.split(':').map(Number);if(h===ch&&m===cm&&localStorage.getItem('class-'+key)!=='1'){notify('forEVAr — hora do mandarim','Eva, seus 30 minutos de conversa em mandarim começam agora. Vamos falar? 🐼');localStorage.setItem('class-'+key,'1')}}function notify(title,body){if(Notification.permission==='granted')new Notification(title,{body})}
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab,.view').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.view).classList.add('active')});$('#listenDialogue').onclick=()=>speak(dialogues[state.index].zh);$('#recordDialogue').onclick=()=>recognize(dialogues[state.index].zh,$('#speechResult'));$('#showHelp').onclick=()=>$('#helpBox').classList.toggle('hidden');$('#nextDialogue').onclick=()=>{state.index=(state.index+1)%dialogues.length;save();renderDialogue()};$('#prevDialogue').onclick=()=>{state.index=Math.max(0,state.index-1);save();renderDialogue()};$('#startClass').onclick=startTimer;Object.keys(vocab).forEach(c=>$('#category').add(new Option(c,c)));$('#category').onchange=renderWords;$('#classTime').onchange=e=>{state.classTime=e.target.value;save()};$('#addOff').onclick=()=>{const d=$('#offDate').value;if(d&&!state.offDays.includes(d)){state.offDays.push(d);save();renderRoutine()}};$('#enableNotifications').onclick=async()=>{if(!('Notification'in window)){alert('Este navegador não oferece notificações.');return}const p=await Notification.requestPermission();alert(p==='granted'?'Notificações ativadas neste aparelho.':'A permissão não foi concedida.')};renderDialogue();renderWords();renderRoutine();renderStats();scheduleCheck();setInterval(scheduleCheck,30000);
